version: "3.8"

services:
  container1:
    build: ./app
    container_name: nodejs_app
    restart: always
    volumes:
      - ./app:/home/ubuntu/backendserver/app/
      - /app/node_modules
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=7872
      - DB_NAME=k2wi
  container2:
    image: nginx:latest
    restart: always
    container_name: nginx_proxy
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - container1
    
  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=7872
      - POSTGRES_DB=k2wi
    ports:
      - "8899:8899"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata: